name: fundsy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  flutter_native_splash: ^2.4.4
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Bassa
      fonts:
        - asset: fonts/NotoSansBassaVah-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansBassaVah-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansBassaVah-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansBassaVah-SemiBold.ttf
          weight: 600

flutter_native_splash:
  color: "#122B14"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    color: "#122B14"
